# 심장내과

[Ekg]
정상 ekg 읽는 법. 
V1에서 S만 보여. 뭐지? 정상이 과장된 상태. LVH다..
LBBB wide qrs
wpw - short pr
lv infarct. ant Q, reciprocal. 
RBBB RVH WPW RIGHT. MI POST
LBBB LVH WPW LEFT. MI ANT
st elevation. pericarditis. normal male pattern
T wave inversion. LBBB환자에서 T inv가 있는데 추후에 qrs방향과 맞게 바뀌었으면 infarct의심해야 한다. 


[Echo 송재관] 
초음파 60년전. 
Long axis.
Short axis. Apical view. Subxyphoid view. 
SAM. w LVOT. 
Pulsed doppler. 
앵두같은 MS. 
2.5Hz TTE. 해상도 높으면 penetration이 낮다. 
Effort chest pain. 

Cardiac CT 연세대 최병욱

[Chest pain 연세의대]
Stress test? 한번더 잘 생각해 보자...
특징적인 angina | atypical angina
CCS angina. III,IV이상을 typical
Resting angina | Increasing angina
TMT? Treadmill test
Non invasive risk stratification 위험군- ST depression at stage | Exercise induced VT/VF
Early invasive diagnostic W/U | Strict warning 언제든지 잘못될 수 있다
!!! Arrest & CPR - Careful hx -> 실제로는 간단한 환자가 아니었어..!! NSTEMI (DM+HTN)
!!! Early invasive - Resting angina | CHF symptoms, S3 gallop | EF<40% | VT | Vital instability | TnT(+) | TIMI&GRACE score가 높은 경우
쓰라리다. 욱신거린다. 하루종일 아파. 여기가 아파. (비전형적) VS 돌로 누른 듯 묵직. (전형적)

괜찮은 줄 알았던 사람인데 알고보니 D-DIMER(+) -> PTE
전혀 괜찮을 줄 알았는데 알고보니 Aortic dissection
게이 | 37남 | vasospastic angina? | 그러나 당일 오전 악화된 통증은? 갑자기 나타난 고혈압? | 이차성 고혈압??인가? | Renovascular -> Aortic dissection....으로 최종 진단됨. class B
Take home message - CT 찍는걸 주저하지 마라.




김영탁 - 울산의대 "invasive and functional eval of IHD"
증상없으면 angiography or CT angio -> inappropriate!
기능적 ischemia
침습적 검사 - Good|anatomic information, Tx+Dx vs Bad|hospitalization, cost
FFR - 0.75이하이면 significant stenosis
DEFER study-FFR>0.75일때 - 괜찮아.. 이걸 근거로 PCI할 경우 생존율 증가. INCIDENCE 감소
FFR이 치료 방향을 결정해 준다.
성인 남자는 흉통이 있으면 TEST해야한다. INTERMEDIATE RISK라고 할 지라도.. 해봐야 한다. 젊은 여자는 안해도 돼.
CARDIAC IMAGING - STRESS EKG못할 경우에 유용. 운동부하 심전도는 병변의 위치 알 수 없다.
ANGINA 보다 PERFUSION의 감소는 먼저 DETECT 할 수 있다. 
Cardiac 엠알은 비싸고 관상동맥 보기엔 좋지 않다.
!!! FFR-CT는 간접적이지만 Radiation적다. computational fluid dynamics.
sensitivity(있으면 있다) 높다. specificity(없으면 없다) 낮다.
허혈 여부가 중요.  SPECT가 많이 쓰이고 있다.


[치료 - 협심증 - 울산의대 안정민]
약물치료 + 혈관재개통 또는 수술 | 딱 두가지다!
!!! 안정형 협심증 - 약물이나 스텐트나 사망률은 완전히 같음 (7년) - 스텐트 할 필요 전혀 없음
!!! STICH - 수술과 모탈리티 차이 없어.
ASPIRIN - CAD, CVA, CABG - REDUCTION OF DEATH
Clopidogrel - death, MI, stroke ASA보다 낮춰줘야함. 출혈 경향은 좀더 크다.
!!! DUAL ANTIPLATELET이 중요하다.
BB - SA에서 좋다
ACEI - NO ANTI ANGINA EFFECT | HTN, DM, 신장기능 안좋을때 꼭 써야함.
NITRATE - 심장에 인삼같은 약이다. BB,CCB와 함께 ANGINA완화함
STATIN - 굉장히 좋은 약. 필수적임.
!!! OMT ( optimal medical Tx) - 1개 statin. BB. ACEi/ARB. 네개 꼭 써야한다!!! 50%도 안하고 있다. 잘 챙겨야 한다.
하지마라. - estrogen, Vit C, Vit A 등은 증거가 없고 해로울 수도 있다.
두단계 - 허벤, 베라파밀 Non-DHP CCB + BB -> Statin
TMT Gr3 잘 하면 약물. 1단계 페일하면 invasive 
!!! non invasive functional study 해야 한다. - risk stratification해서 약물치료 or 스텐트(수술)해야할지 !!!
조지 부시 - 증상 없는데 스텐트 해야할까? 안해도 된다. 현재 기준으로는 over-use stent
무분별한 CAG가 많으므로 증상없으면 안해도 돼. 저위험에서도 안해도 됌
ISCHEMIA연구 - CAG 없이 약물 혹은 혈관재개통? - 무엇이 좋을지...
Everlorimus-eluting stent 
angiography뿐만 아니라 FFR guided PCI를 해야한다. FAME연구 - 스텐트 과다 사용을 낮춰준다.
BRS - 몸에서 저절로 흡수되어 사라지는 스텐트 - 5년 뒤엔 완전히 없어져.
PCI VS CABG | 단순병변 VS 복잡병원 (3VD, LM+2 OR 3VD)
NIFS - NON INV FUNC STUDY (TMT,THALLIUM) - LOW(OMT) VS HIGH (CAG+OMT) - PCI, CABG

[ACS UPDATED MANAGEMENT]
히드라 
80세 이후엔 암으론 잘 안죽어. 혈관으로...
!!! 레벨 A- ANTI PLT, STATIN, ANTI-HTN !!!
!!! TROPONIN - 0.04가 기준이다!!!
애매하면 coronary CT 찍어라. -> suspicious ACS at ER. 
20분이상 STE. 2개 리드에서..
10% | 20% | 10% - stemi|NSTEMI|UA
P2Y12 - PLT ACTIVATION BLOCK - TICAGRELOR,PRASUGRL,CLOPIDOGREL(STEMI)
IABP X 쓰지마라.(AMI with mechanical Cx-VSD)  - NE!!!(LEVOPHED) - DOPAMINE 안쓴다. 
!!! TIMI쓰지마라. GRACE (ACS RISK SCORE 2.0)가 좋은거다!!! 
Time is Muscle. 
5% mortality - door-to-door time 줄어도 동일하다. !!!! 환자가 빨리 와야된다. !!!!
혈전용해제는 뇌출혈 없으면 다 해야된다.
!!! statin.  dual. BB

정리
Medical Tx가 중요하다! - survival rate를 높이는 스텐트는 제한적인 population에만 적용될 수 있다.
청진기보다 초음파보는게 중요한 시대가 왔다. 청진기가 필요없다.
subjective Sx

# 심장내과 3부


[Mitral Valve Disease - Dx and Management - 김덕원(울산의대)]
MR - 피가 역류하므로 좌심방 좌심실 커진다. 심부전
1차성 - 퇴행성, 류마틱, 선천적, 심내막염 | 2차성 
초음파검사가 중요하다. 병기는 A/B/C/D - C/D는 SEVERE.
Primary Severe MR - anatomy. Hemodynamics. LV enlargement. 
Echo for degenerative MR - myxomatous degeneration. ERO>0.4cm^2 | LV EF<60%
MV repair - 사망률 줄였다. 
64여 - known DM - Dyspnea(+) - 4MA - global hypokinesia (akinetic portion) - structurally normal - tethering (땡겨지는 현상) - Severe functional MR. ERO >0.2cm^2 
!!! 1차성은 적극적으로 치료, 수술 고려한다. 그렇다면 2차성은?? 여전히 수술 후 사망률이 높다. 좌심실이 중요한 예후인자이다. 수술후 생존률에 이득이 있지는 않아. 이득이 제한적임 !!!
MS - natural hx. - 진행이 매우 느리다. INDOLENT. 좌심방에 PR. OVERLOAD - 그러나 심방세동이 발생하면 갑자기 안좋아지는 경우가 있다. 그러나 대체로 예후 좋다. 증상없으면 두고보는데 세동 생기는지 잘 관찰해야 한다. AFIB 생기면 STROKE생길 확률 매우 높아진다 (치료안하면 >90%)
PMV가능할 경우 PMBC- PERCU MITRAL BALLOON COMMISUROTOMY.  불가능할 경우...
증상없는 심한 MS. PMBC - Septal puncture- 가장 위험할 수 있다. hemopericardium생길 가능성이 있다. embolism. severe MR.등의 합병증이 생길 수 있다. 이미 혈전이 있으면! 하면 안된다. 
합병증 줄이려면 - case operation experience가 중요하다 | patient selection 잘해야 한다. Early PMC
[송종민 - Aortic Valve Ds - Dx and Mx]
AS - ETIOLOGY - degenerattion. calcification. thickening. 열릴수가 없는 상태이다. bicuspid leaflet. 
Pr. gradient of as. 크면 클수록 AS심한거다. 요즘엔 도플러를 통해 버눌리 방정식으로 구한다.
AV 속도가 중요한 위험인자. 
VERY SEVERE MS+LOW SURGICAL RISK - 미리 수술하는게 가능. 
!!! TAVI VS Medical Tx TAVI가 좋다 (PARTNER Trial) 2011 NEJM TAVR vs SAVR 차이 없다 - 요즘엔 CORE VALVE(Self expandable 늘어나는 신축성 있는거)로 해보니 TAVR이 모든 면에서 좋아!
AR - 수치화 하는게 중요하다!  복부대동맥에서도 보이면 severe
수술 늦게하면 나쁘다.. 너무 늦게하면 좋지 않아.
EF낮으면 예후 나쁨. LVESD낮으면 예후 나쁨. 
VASODILATOR (NIFEDIPINE) - 초기에는 좋다! - 이후엔 별 차이 없다. AR+HTN은 약물치료해야한다. 수술해야하는건 결국 고려해야 한다. 
[SCD Evaluation - 성균관대 박경민]
갑자기 쓰러짐. 왜 쓰러진걸까? Normal coronary일때 - 부정맥 전문의들에게 큰 문제가 생긴 것임.
DDX OF SYNCOPE | CARDIAC 20%이상의 돌연사 확률 (1년 이내)
EVALUATION - Hx. FHx. Drug- prolonging QT interval(cisapride, 초오aconitum - 한약 먹었는지 물어봐야) 돌연사의 가족력!!! -> 미주신경성 (복부, 식은땀, 회복기때 구역, 서있을때 실신) vs 심장(누웠을때, 운동중)
비침습적 - EKG. precordial lead. - 전해질? | 초음파 HCMP, VHD, LV, ARVC/D | MR | HOLTER, EVENT RECORDER | Implantable event recorder(3년) 
침습적 - cardiac cath. - spasm test(젊은 사람의 경우)
EPS 유발시킬 수 있는가? 잘 안되는 경우도 20-30%된다. 
ㄱ브루가다 - Precordial lead ST가 자주 변하는 경우
증상: 실신 - 피지컬, 이미징 정상 - ECG - FLECAINIDE, PROCAINAMIDE - NA CHANNEL BLOCK. CURVED PATTERN이면 확진가능하다. SADDLEBACK PATTERN 이면 좀더 두고봐야한다.
Long QT syndrome - QTc - RR interval QT/sqrt(RR interval) - 소타롤 등등, 420mm이상이면 롱. - 젊은 사람 - TdT 잘 생긴다. 롱큐티에서 TDT 잘 생길 수 있어. 저칼륨, 저마그네슘, 할돌 항고혈압제, 에리스로마이신
LQS 1 exercise(swimming) | 2(깜짝 놀랄때) | 3(잠자다가 실신) - 처방 : 베타블로커, 수영 덜해라. 약물 줄여라. BB - LQS 1,2에 잘 듣는다.
급사가족력. 젊은 남자. VTACHY. DC CARDIOVERSION 후 심전도에 찌글찌글 - ARVD/ARVC - SUDDEN CARDIAC DEATH가능함. EPSILON WAVE. ARVD진단기준. - 영상검사. BX - 도움된다. 심실 제세동기 삽입이 치료!
실신. 젊은 여자. 아무것도 안나와. 전기생리학적 검사 거부. 모니터 삽입. VT - 심실제세동기 삽입. 


