
# Bioimaging 2016-04-29

Lee, Hanmi | Value of Bioimaging for global drug development
B-raf inhibitor | targeted inhibitor
* Anatomic-functional->molecular(optical imaging, IVIS, SPECT, microMR,PET,CT
* Bioimaging platform | PK, Imaging biomarkers, treatment effect, diagnostic tools
* PD-1 | IHC system (digitalized and standardized) immune-oncology - PD-L1 expression - Pembrolizumab (MK-3475) - NSCLC 
* Pembrolizumab for the Treatment of Non–Small-Cell Lung Cancer http://www.nejm.org/doi/full/10.1056/NEJMoa1501824
* Biomarker discovery - surrogate marker & PK/PD
* Human PK | exposure response PK-PD(Target engagement) | Exposure-safety 
[HM95573] BRAF-KRASmut inhibitor
http://www.newstown.co.kr/news/articleView.html?idxno=185364
한미약품이 개발 중인 차세대 표적항암제 HM95573이 국내 1상 임상시험에 돌입한다.

한미약품(대표이사 이관순)은 최근 HM95573에 대한 임상시험 승인 신청서를 식품의약품안전처에 제출하고, 내년부터 서울아산병원에서 흑색종 등 고형암 환자를 대상으로 임상 1상에 돌입한다고 5일 밝혔다.

HM95573은 암세포 증식 및 성장에 관여하는 변이성 RAF 및 RAS 단백질을 선택적으로 강하게 억제하는 표적항암제로, 기존 약물에 반응하지 않거나 부작용이 큰 환자들에게 투여할 수 있는 2세대 RAF 저해제 약물로 개발되고 있다.

한미약품은 이번 임상을 통해 고형암 환자에서 HM95573의 안전성과 내약성을 평가해 최대 내약용량 등을 결정하며 종양반응률, 최대 종양크기 변화율, 질병조절율 등을 관찰하게 된다.

약물의 종양 반응과 관련한 시험 대상은 변이성 B-RAF, 변이성 K-RAS 및 변이성 N-RAS 단백질을 가지고 있는 흑색종, 대장암, 간암 또는 비소세포폐암 등 환자이다.

한미약품 정진아 임상개발 담당이사는 “HM95573은 기존 항암제에서 반응하지 않는 환자들에게 투여할 수 있는 2세대 약물로 개발 중인 표적항암제“라며 “암으로 고통받는 환자들에게 혁신적인 치료제가 될 수 있도록 최선을 다해 개발하겠다“고 밝혔다.

한편, 이번 HM95573 개발은 지난 2013년 6월부터 보건복지부의 ‘국산 희귀의약품 연구개발 과제’로 선정돼 보건의료기술연구개발사업의 지원을 받아 추진된 것이다.

한미약품은 HM95573을 비롯해 암세포 성장에 관여하는 EGFR(상피세포성장인자) 돌연변이만을 선택적으로 억제하는 ‘HM61713’, EGFR 수용체의 신호전달을 차단하는 포지오티닙(Poziotinib) 등 3건의 표적항암제 파이프라인을 보유하고 있다.
https://clinicaltrials.gov/ct2/show/NCT02405065

* BRAF Mutant Melanoma Only -> Vemurafenib, Dabrafenib
* FRET - measures signaling
* PD marker - efficacious dose = 300mg BID | MODELING | POP-PK
* expected efficacious exposure ~130k c.a
* Pan EFGR inhibitor or - Afatinib, Erlotinib - live in vivo imaging
* Summary - longitudinal in-vivo imaging 
* 28 programs | Total R&D center : 493
[Q&A]
Companion diagnostics - targeting angiogenesis

# 신약개발을 위한 FDA의 바이오이미징 표준화 프로그램 | 
## 김정곤 Center for Bioimaging of New Drug Development AMC
* Qualification 
* 왜 이미징바이오마커에 대해서 qualification 필요한가?
* Bioimaging의 논문수는 기하급수적으로 증가중
* 누구나 인정가능한건가?
* Biomarker - a characteristics that is objectively measured and evaluated as an indicator of normal biological proc, pathogenic proc or pharmacologic responses to a therapeutic agent
* Surrogate endpoint - a biomarker that is intended to serve as a substitute for a clinical meaningful endpoint
* 최종목표 correlated to clinical outcome
* Validation = reproducibility | 확산강조영상DWI - tumor에서 measure할 수 있나?
* Qualification = linking a biomarker with biological proc
* Trial investigators often do not know - where | what QC testing performed? | What sources of bias & uncertainty in measurements
* Inadequate QC
* Inconsistencies in the imaging protocol
* FDA Drug Development Tools DDT Qualification Programs
* http://www.fda.gov/Drugs/DevelopmentApprovalProcess/DrugDevelopmentToolsQualificationProgram/
* CDER | CDRH - FDA에서 관장.
* OND - 약물 개발 과정의 규제 감독. 신약 판매 허가. 6개의 사무실로 구성
* http://www.fda.gov/AboutFDA/CentersOffices/OfficeofMedicalProductsandTobacco/CDER/ucm184426.htm 
* 궁극적으로 encouraging
* Biomarker Qualification Program
* http://www.fda.gov/Drugs/DevelopmentApprovalProcess/DrugDevelopmentToolsQualificationProgram/ucm284076.htm 
* http://www.fda.gov/downloads/drugs/guidancecomplianceregulatoryinformation/guidances/ucm230597.pdf 
* Qualification Process for Drug Development Tools APPENDIX 1: QUALIFICATION PROCESS
* European Medicine Agency | 일본에도 있다.
* Current Status of Imaging BQ 6/16 BQ submissions are on imaging biomarkers
* 



