---
title: 2016 ACREP
layout: post
categories: Conferences
comments: true
---

# ACREP
## Observational Study
* Speaker 이무송

### Contents
* Cohort study
* RR $$ \frac{\frac{a}{a+b}}{\frac{c}{c+d}} $$
* 단점 - F/U loss, 재발에 대해서 연구 어렵다.
* 연구 대상 수 산출 방법 - Nomogram, 수식적용, 컴퓨터 PASS 2016
* PCORI.org - conduct of Registry
* Cohort는 F/U을 전제로 해서 한다. Retrospective Chart-review

## Observational Study의 Pitfall 및 이를 극복하기 위한 방법
* Speaker: 임영석 교수님

### Experimental study? Yes
#### Randomized design? (interventional)- No
* NR CLINICAL trial
* Time series
* PHASE 1

#### Randomized design? (interventional)- Yes
* Clinical Trial
* Community Trial
* Crossover design

### Experimental study? No
#### Comparison group? No = Observational study
* Prevalence / incidence,
* time trend,
* case series,
* case reoprt

#### Comparison group? Yes = Analytical study
* Cohort study,
* case-control study,
* cross-sectional study,
* ecologic study,
* PMS
* 두군을 비교하는가 안하는가가 중요한 기준이 된다.

### Contents
* research question -(design)- study plan -(implement)- actual study
* findings in the study -(infer)- truth in the study -(infer)- truth in the universe
* 위암, 대장, 폐암 - post op outcome을 통채로 비교하면 안된다.
* internal validity & external validity(generalization)
* PICO anatomy #####
  * patient/population/problemn
  * Intervention
  * Comparison
  * Outcome
* Gold standard of clinical studies - RCT
  * Sample - randomization (Treated / Control)
* Research question - interesting, important, critical
* Good research question - FINER - Feasible, Interesting, Novel, Ethical, Relevant
* Feasible / Ethical / Relevant 가장 중요한 면
* Prospective Cohort Study -
* Case-control study - 뒤로 간다. 병원에서 case-control 하는 경우는 사망여부. Outcome인 경우가 많다. disease있고 없고가 아니라.
  * 재발에 대한 - 환자군/대조군을 모아서. 그럼 어떻게 대조군 설정한건가?? 이런 것을 정할때 bias가 많이 발생하게 된다.
* Historical cohort - Cohort assembled-(f/u)->Outcome
  * 2000-2010 HCC 초치료 근치적 수술적 절제술 받은 환자들의 명단을 확보.
  * ITT analysis할때 반드시 필요하다.
  * 5년 이상 관찰한 것이 있어.
* Mimic those of clinical trials
  * Internal validity를 높여야 한다. restricted cohort / NEJM 2000;342:1887
  * IIT 분석을 해라.
* Chance(Random Error) vs Bias(Systematic Error)
  * association / cause를 비교해야.
* Confounder
  * biasd와는 좀 다르다. 미리 의식하고 물어보기 전엔 절대 알수 없다. 미리 질환에 대해 잘 알고있는 연구자여야만 찾을 수 있다.
  * Example : smoking - alcohol - heart disease
* What is the effect of long-term tx(>5y) with a potent oral antiviral agent(entecavir)(I) in patients with chronic hep B(P)
* FDA, 식약처는 Surrogate marker를 가지고 허가를 내준다. (조직학적 개선,) - 이것과 환자의 outcome을 정말로 개선시키는건가? 이건 observational study에서만 찾을 수 있다. historical cohort
* Zero time No treatment control
* Endpoint ascertainment - 재발이 문제가 된다. 무엇으로 재발을 판정할 것인가? MR? CT? 검사간격을 얼마로 했니? 누구도 시비 못할 것으로 outcome measure하는 것이 좋다. (예를 들어 사망의 경우)
* PP vs ITT
  * ITT - which treatment option is best at the time decision must be made? - FDA에서 ITT만 인정을 한다.
  * Explanatory
* Multivariable Cox PH Analysis - (Event 수를 적어야 한다.) Univariate analysis만으로는 부족.
* Multivariate analysis -
* Propensity score - SPSS로 가능. 양군간 matching - 쌍을 갖춘다. 같은 수로 나온다. 이때는 univariate할 수 있다.
* "consistently observed by unadjusted."  - obs study는 의심을 많이 받기 때문에. 이런 분석을 하는 것이 좋다.
* Gadoxetic - liver specific contrast agent
  * 2647patients->700명 수술 가능. - surrogate marker - CT에서 못본걸 MR에서 찾았다. | Cost-effectiveness - 무조건 survival. Propensity matching - Inverse Probability Weighing (IPTW)
    1. Unadjsted
    2. mutivariable
    3. IPTW
    4. Propensity
  * 제목의 중요성. JCO (IF 21) - Hepatology (IF 11.7) - Gut (IF 14.921) (early rejection so far) - GE (IF 18.187) (accepted with more general terms in the title)

### Conclusion
* mimic as closely as possible in RCT

## Diagnostic test & Biomarker Study
* Speaker: 박성호 - 영상의학과

### Contents - Diagnostic test
* DTA sutdy
* Prevalence낮으면
* 횡으로 본다. Predictive Value - Prevalence에 영향을 받는다. Pre올라가면 PPV올라가. NPV낮아져.
* odds ratio - prevalence에 영향을 안받는다. intrinsic parameter로 많이 씀.
* case-control study vs cross-sectional study [옛날 용어]
* Cochrane - case-control type accuracy study vs cohort type accuracy study
* NECA - diagnostic case-control study vs diagnostic cohort study
* Area under ROC curve - C statistics
* Youden index - sens spec 더해서 빼기 1 Youden J statistic
* Least Euclidean distance from (0,1) 거리가 최소되는 점. - 쉬운개념
* diagnostic accuracy - 시각적으로 어떻게 구성하는지가 중요함.
* McNemar test
* Comparing two proportions (2x2) - unpaired(fisher,Chi2), paired (McNemar)

### Contents - Biomarker
* Biomarker
	* Classifier / Prognostic / Predictive / Monitoring
* Petal et al. MRI-detected tumor response for locally advanced rectal cancer predicts survival outcomes
* Machtay et al. Prediction of survival
	* Prospective
	* S III lung cancer eligible for CCRT
	* Endpoint : overall survival
	* SUV
* Hylton et al.
	* Prospective
	* Index: functional tumor volume measured with pre-surgery breast MRI
	* Comparator: post-surgical pathologic complete response(PCR)
	* Modified C-statistics(ROC) - diagnosis는 있다 없다로 나온다. survival은 time to event - 각각의 time point마다 diagnosis 유사한 통계량이 나와서 그걸 summation
* Studies of predictive accuracy
	* Two approaches - Time-to-event / event by a fixed time
	* Event by a fixed time - Sn Sp ROC - Accuracy study와 유사한 것으로 된다.
* 더 impact있는 것. - randomization을 테스트 후에 할 것인가 아니면 전에 할 것인가? 전에 하는 것이 더 임팩트 있다. 왜냐하면 테스트(+)이면 치료 들어가는 경우가 많기 때문이다.
* 후자에 해당하는 (더 임팩트있는) 스터디의 예.
* Monitoring biomarker
	* Correlation between x and y / delta x and delta y
	* Delta를 보는 것이 중요하다.

## 2차 자료원을 이용한 역학 연구군
* Speaker: 예방의학교실/의학통계학과 김화정
* NEJM 2006, BMI and mortality
* 이차자료원 : 특정한 연구목적으로 수집되지 않은 자료
* 공공데이터 - 정부
* 국건영 심평원 자료 - 생각보다 manage하기 쉽지 않다.
* HIRA DB - 건강보험청구자료
* NHISS 국민건강보험자료 공유서비스
* 보건의료 연구에 활용되는 공공데이터
* 장점 : 대규모자료, 장기간 추적관찰. 시간과 비용 절약
* 한국형 - outcomes Research
* NECA에서 자료를 연계해 주겠다 라고 했으나.. 진전이 크지 않음
* 보건의료 빅데이터 개방시스템 - 공공데이터
* 명세서 일반내역 테이블
* 2차자료의 분석은 case-control의 기준 정하기가 어렵다. 금방 분석이 되기 힘듬. Crossvalidation 반드시 해야함.
* 과제신청 - 연구원등록 : 정부3.0에서 검토 자세히 하게됨.
* SAS/R 프로그램.
* 단점 - 5년간의 자료. F/U보기가 힘들어. 진단명의 정확도 문제 - 70%. 에러의 숫자가 클 수 있음.
* 의학통계학과 공공데이터 연구지원 #4639 - 상담, 공공데이터 이용신청, 자료확보, 자료분석, 결과검토
* NHISS 표본연구
* Dramatic decrease in FQ in the pediatric population
* case crossover design
* indication bias - causality - association. confounding by indication

## 대규모 이차 자료원을 이용한 clinical prediction model : individual risk/outcome probability 예측 분석법
* Clinical prediction model
* Framingham risk score
* JAMA - moving from clinical trials to precision Medicine, 2016 Apr 26
* DAPT Trial
* Risk for advanced neoplasia and  likelihood ratios in each risk group within derivation and validation sets
[Derivation and validation of a scoring system to stratify the risk of advanced colorectal neoplasia in asymptomatic adults](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4840411/#!po=38.6364
)  분자:질병있는 / 분모:질병없는 - likelihood ratio
* Assumptions for model development - linear regression, Cox proportional hazard regression(Proportionality of hazard ### This should be confirmed.)

| | linear reg | logi reg| Cox reg|
|-|-|-|-|
|Overall perf| R2 | Nagelkerke r2, brir|the same|
|discrimination ability||C concordance stat(AUC)|Harell C stat, time-dependent AUC|
|Calibratrion|Calibration plot, slope|the same+hosmer-lemeshow|the same|

* C-index 를 사용하여 분석 가능함.  C = number of concordant pairs + 0.5/~~
* 새로운 통계 지표. 2가지. NRI - net eclassification improvement
* Korean J Radiol 2016;17(3);339-350 -> predicted probability - 사망할 확률을 계산할 수 있음.
* Framingham그룹에서 발표됨 2008 통계 저널에

## Web-r.org
* Speaker: 문건웅 가톨릭대학교 성빈센트병원 심장내과

### Contents
* web-r.org
* 로지스틱 리그레션 - 반응(종속)변수 - 설명변수 . 단변량 분석 먼저 나와 univariate logistic regression
* 다변량 분석.
* 생존분석 - 로지스틱 회귀분석과 비슷한것임. - 다른 것은 시간개념이 들어있는 것임. 얼마 있다가 돌아가셨는지 알 수 있음. KM 분석. cutpoint결정해줌.
* 나무분석 - 생존 나무 분석.
* 진단통계
