# Prism

## Morning

### Lim Covariate model

#### Ischemic stroke
- Primary endpoint
- time-to-primary endpoint (time-to-event)
- late recurrence, DM
- Secondary endpoint
- late recurrence
- 통상적인 VPC - K-M plots
- Modeling and simulation analysis of the relationship between lesion recurrence on brain images and clinical recurrence in patients with ischemic stroke http://onlinelibrary.wiley.com/doi/10.1002/jcph.427/abstract `r citep("10.1002/jcph.427")`

#### MR image -> 예후 예측
- mRS (modified Rankin Scale)
- 응급실에 왔을때
- DM - NIH scale 3D Plot
- 광학영상 - preclinical 에서 부터 NONMEM을 사용해서

### FDA - Lee
- http://www.dailypharm.com/News/202010
- [Joga Gobburu](https://www.linkedin.com/in/jogagobburu) - 인도사람
- [Yaning Wang](https://www.linkedin.com/in/yaning-wang-a47192b) - deputy director
- [Vikram Sinha](https://www.linkedin.com/in/vikram-sinha-9a28476)
- math molecular biology - impressive - reviewer
- Office of CP - 7개 division, 1~5 clinical division- 질환별로 - align (DCP) PM(떠오르는 학문) PG division

### Pfizer
- 파리바?
- 크루시파이? - Metz Karlsson과는 아니고..
- 파일러비시니? UW - metrician -> 임상약리에서 뽑았다. (파리바)
- 피터 뮬리건? <-> 아만티아(놀려고 함..)
- 밥 파월 =  임동석 선생님

## PRISM Afternoon
2016.07.12

### Kim
- Modeling
- Buzz words
- M&S
- SP&PMx - MBDD - MIDD - MID3 (Drug discovery and deveopment)
- Lean, apply and confirm
- Case I : use of pk modeling in pre-cilnical stage
- NOAEL : Rat 250mg, dog 500mg/kg
- Target exposure
- Questions - have we selected right starting dose? - FDA
- MRSD (FDA guidance) - following actions were taken
- Proposed FTiH dose were 50mg, 100mg~1200mga
- Dose 5-200mg
- MABEL, maybe a challenge but doable with lower s
- NOAEL - MABEL - allometry = we should use all of these.
- Case II : Use of PK in FTiH study Dose Escalation Stage
- Unexpectedly longer half life (x5)
- everything is impacted. POC study
- Questions arose
- Emax model -> nice when it's adhered to the predicted.
- New formulation development
- Case III : Use of PK in FTiH / BIAL lab, BIOTRIAL research site in Rennes, France
- BIA-102474-101 study design
- SAD 8 cohorts
- SAD -> Food effect -> MAD
- What caused these events - threshold, off-target pharmacology, FAAH inhibition
- TSSC report -> Interesting observation related to PK - elimination HL of BIA is gradually extended. Non-proportionality begins.
- Non-proportionality - SAE probability
- Emax model - 80% !!! 50mg QD
- Recommendation : use of sentinel
- London incident, early human (Prediction)
- Summary - PK, PK/PD modeling and simulation is essential

**Questions**
- 20*10 MAD -> okay 50*5 MAD -> not okay, why?
- Eye drop -> allometry experience?

### Strategic application of PM in global drug development: Experience from Hanmi
- Speaker: Lee Young Mi, Hanmi
- Why do we need PM? - biologically effective dose, earlier translational risk assessment, safety margin(systemic and quantitative translation of animal models to clinic), Pre-clinical modeling to guide clinical dosing, enhancing early stage decision-making, evidence-based decision making and accelerate drug approval
- Systemic and quantitative translational research. PK&PD -> target occupancy, mechanism
- Human PK projections - LAPSCOVERY development strategy
- DRUG+AGLYCOSYLATED FC - Flexible linker
- Longer duration - once weekly, once monthly -> FcRn mediated endothelium recycling / avoiding renal filtration!!!!! - Kidney failure patient can receive the LAPSCOVERY drug. Long-acting protein/peptide
- GLP1, insulin, somatostatin : peptide
- Protein : hGH, IFNa, mG-CSF
- Exendin-4 analog, IFNa -> protein
- LAPSInsulin A (analog of insuling) -> longer HL -> human serum conc vs time profile
- Case 2. Targeted therapy & surrogate PD marker
- It is important to select PD marker!!! Some cancer - hard to choose PD marker. (Eg. Lung ca)
- phosphoEGFR - OLITA (olmutinib) - breakthrough theray designation (FDA) by US FDA - phase II BTD -> modeling when the n= increased??? -> licensed out to Behringer Ingelheim
- Exposure-Response : PK-PD
-  Recommended dose selection - CRITICAL!!!
- PK-PD Xenograft
- Targeted therapy & biomarkers - BRAF/KRASmut inhibitor
- Next gen RAF inhibitor(PanRAF) (<-> Classical RAF inhibitor = rebound MAPK reacitivation)
- Methods difference (pMEK), (pERK) -> aided dose seletion (lower exposure and the same PD marker)
- HM95573 and Cobimetinib in MAPK activated HCC cell lines
- combination -> can lower dose

### MBDD
- Speaker: Lim
- MBDD (Learn & confirm cycle) course run
- Information management tool = Modeling
- Quantitative information (GO/NO-GO decision)
- Various and diverse information
- Quick win, fast fail - PK/PD modeling and simulation
- Abundance of drug discovery - preclinical development (Mechanism-based biomarker, imaging biomarker) - accelerated PoC (IIb/IIa) - confirmation, dose finding
- System-specific parameters, drug-specific parameters, structural model
- Extrapolation
- Quantify the exposure in remote and/or inaccessible
- Allometry vs PBPK
- assumes that the nly diff between human and the other mammals is size = imprecise, mono-exponential elimination
- DHP107 - IV paclitaxel
- 480mg/m2 was the most common MTD(Maximal Tolerability Dose) in virtual phase 1 trial for DHP107
- Case II - Ticagrelor PD
- ticagrelor and AR-C124910XX
- Maximal platelet aggregation
- Case III - Early characterization of an antibiotics using bacterial time kill assays and human PK study
- Preclinical PD + Human PK => Predict human PD
- Monte-Carlo simulation using PK/PD model
- Case IV - integrative PK/PD Model
- 16182HanLimPyung441) - MFDS
- Integrative, mechanistic PK/PD model
- Tumor size

**Questions**
- NONMEM -> PBPK? ADAPT?(Program?)
- THETA, ETA (60-70) Generally 40

### Pharmacometric information in drug label
- Speaker : Bae
- Ocaliva (obeticholic acid tablets)
- oral use | initial U.S. Approval 2016.05.27 - FXR agonist - Tx of PBC - Omega matrix -> POPPK analysis
- NUPLAZID (pimavanserin)
- Parkinson's ds psychosis
- Oral

- POP modeling 구체적목적
- fixed effects covariate 찾는다
- interintra subject random variability의 크기를 평가
- 개인별 pk,pd
- 농도, 폭로, 반응/효과, 유해반응 simulation하기 위한 모형을 구축
- Total variability
- Fixed portion + random portion
- fixed effect = explainable
- Eta (interindividual (random) variability)
- NONMEM
- F = function of (theta, , covariates) # Fixed
- Y = function of (F, epsilon)  # eta=0(무시)하면서 예측한경우 = Typical prediction
- theta = constant, nu~MVN(0,omega), eta~MVN(0, sigma) 확률변수
- Covariates - usually dose, time, demographics and other measurement
- Epsilon = express homoscedastic, proportional, exponential or combined errors
- Dose,time = covariate (statistics)
- Eta - Realized Eta = 0이 아닌 숫자화된 Eta (inter individual)고려해서 한거 - F:IPRE F:PRED(Typical prediction)
- Population Concept
- Eur J Pediatr(2015) 174:1671-8 Prediction of plasma caffeine concentrations in young adolescents following ingestion of caffeinated energy drinks: a Monte Carlo simulation - `r citep("10.1007/s00431-015-2581-x")`
- CL, Vd(실제론 둘이 연관이 있다.) -> Correlation을 유지한 채로 sampling 되도록. MVN
- Pharmacometric Review : pop PK-PD model
- Visual Predicted Check
- Prediction band

> The fast-growing consumption of caffeinated energy drinks (CEDs) is linked to increasing reports of caffeine intoxication in adolescents. There is limited data available regarding plasma caffeine concentrations in this population after CED intake and the potential implications for caffeine-related toxicity. This study was an in silico population pharmacokinetic analysis of caffeine. Population pharmacokinetic model of oral caffeine was derived from a previous study of healthy male volunteers. Maximal plasma caffeine concentration (C max) profiles following ingestion of one or two servings of popular CEDs were predicted using Monte Carlo simulation and available population body weight data of 10–15-year-old Korean adolescents. Caffeine C max values were positively correlated with the amount of caffeine ingested in CEDs and negatively correlated with body weight. The median (range) C max profiles varied from a low of 1.2 (0.5–2.6) mg/L to a concentration that is potentially associated with harmful caffeine-related effects of 25.4 (8.1–55.6) mg/L. A subgroup of female 10–11-year-old subjects exhibited the highest caffeine exposure profiles.
> Conclusion: These data indicate that CED ingestion can increase the risk of serious caffeine intoxication in young adolescents, particularly those with low body mass.

### Pharmacometrics in Dose Optimization
- Speaker : Lee, FDA
- Interindividual variability (PD, PK)
- Secukinumab (Cosentyx) - target population
- https://en.wikipedia.org/wiki/Secukinumab (Novartis)
- Example of dose optimization
- IL-17(A) - Etanercept, infliximab, adalimumab(humira, shallow), ustekinumab = biologics
- 몸무게 크면
- IgA, 4 Phase III, (2 of them were pivotal study)
- PMC - post marketing commitment
- the higher conc. => the higher incidence of infections (tolerable)
- Edoxaban (흥미로운 약물)
- NOAC - New Oral Anti-coagulants (4th)
- 1st rivaroxaban, 2nd dabigatran(issue-EMA), 3rd apixaban
- Ace Meeting?
- Normal - Mild - Moderate
- Exposure - response relationships (Efficacy-Stroke, safety-bleeding)
- Benefir-risk relationship is not novel. (Dabigatran: RE-LY trial)
- exposure-response relationship PK matching.

```{r bibtex, echo = FALSE}
write.bibtex(file="References.bib")
```
