---
title: 2016 독성학 전문교육과정 요약
---
# Toxicology 2016 
- author: 한성필
- date: 2016-08-22 ~ 2016-08-23
- venue: 숙명여자대학교 백주년기념관 2층 컨벤션 센터

## Key links
- [한국독성학회](http://www.toxmut.or.kr/)
- [Benchmarks in Toxicology](
https://www.toxicology.org/about/history/docs/poster_Benchmark.pdf)    
- [ICH guideline](http://www.ich.org/products/guidelines.html)
- [의약품의 임상시험 수행과 품목허가를 위한 비임상시험가이드라인](http://drug.mfds.go.kr/Data/KO_NO/r88w76h15j1a68p96o45d64s58h22o81p54b66q55j14u82.pdf)
- [생물의약품 비임상시험 가이드라인(2014)](www.nifds.go.kr/nifds/08_part/part02_c_b.jsp?mode=view&article_no=7483&pager.offset=0&board_no=167)

## Session I 2016-08-22 
### 독성학 개론 및 발현기전 !!!! {.tabset}
- 홍진태: 충북대학교
- 독성학에 많은 분야가 있다. (규제독성학 : 가습기살균제)
- Toxin vs Toxicant man-made
- Toxicity, Hazard(상태), Safety(risk의 반대 개념), Risk(probability), Risk Assessment
- Idiosyncratic reaction, delayed toxicity(중국에서 온 조류, 잔류성 농약 먹고 우리나라 와서 독성)
- 화학적 상호작용 - Additive, synergistic, potentiation, antagonism
- **용량-반응관계** - 유해성 평가에서 중요한 factor - Dose-response - sigmoid하게 나타난다. 그룹별로 나타난걸 Quantal이라고 한다.
    + 직선형으로 표현할 수도 있다.
    + 기울기도 봐야 한다. B는 다루기가 힘든 약 (Steep) LD50는 같을 지라도 주의해야 한다.
- 효력Potency vs 효능efficacy
    + Morphine / aspirin
- Therapeutic index - LD~50~/ED~50~
- Margin of safety - LD~1~/ED~99~    
- Margin of exposure    = exposure level / TD~10~
- Subchronic / chronic dose response - Liver necrosis - LOAEL NOAEL(No observed AE level)
    + ADI, RfD, TDI 만성 노출에 대한 허용치를 결정하는 전형적인 시발점
    + Benchmark dose (모델링을 사용해서 결정)    
- threshold
- 독성 영향 인자
    + selective
    + 생체내 전환    
    + malathion : 사람 vs 곤충(곤충에만 축적)
    + 빈도, 농도, 용량, 부위, 경로, 시각(chronopharmacology)-마우스 KCN치사율에 대한 circadian susceptibility(심박동 낮고 안정화된 아침에 투약)
    + 내인성 인자: 종, 성별, 연령, 체중/신체구성
- 동물 독성 연구 - 동물에서의 노출과 영향을 연구
    + TCDD에 노출된 rat의 종양 발생    
- 독성 시험의 유형 - 단회, 반복 투여 독성 시험, 유전 독성, 면역 독성, 발암성 시험, 국소 독성 시험, 메커니즘 연구, OMICS 활용 독성
- Mechanism of Toxicity
    + Delivery, Reaction, Toxicity, Repair
- Exposure of Toxic chemicals -> Ultimate toxicant + Target molecule
- Type of Ultimate toxicants and their sources 
    + 대사체가 xenobiotic toxicant 
    + Reactive oxygen or nitrogen species as ultimate toxicants
    + **Endogenous compounds as ultimate toxicants (lipid - peroxidation, Bilirubin)**    
- Distribution (Specialized transport - ochratoxi, MPTP into DA neuron
- Accumulation (Away from the target - MDR)    
- Excretion vs reabsorption 
    + Excretion (volatile, non-volatile) 
    + reabsorption (tubular fluid reabsorption, carrier in kidney, intestinal lumen) - 우리 몸에선 약산, 약알칼리, 중성의 약물 - PH가 중요하다. PKA
         + salicylic acid (알칼리에서 reabs 감소), morphine(산성에서 reabs 감소)
- Toxication vs detoxication
    + electrophiles : nonionic, cationic
    + nucleophiles :    amygdalin -> cyanide
    + free radical formation
        + Xenobiotics -> super oxide
        + P450 reductase PQ, DR, NF 전자를 하나 받아서 reduct한 효소로 바뀐게 산소와 반응해서 free radical 만들게 된다. reduce된다. (전자빠지면서) reactant가 된다.
        + Endogenous sources of O2    
        + One electron oxidation by peroxidases or P450
        + superoxide anion radical toxication
    + Detoxication of free radical
        + SOD, Catalase, GPX, HO(ineffective), ONOO- : free radical scavenge
- Reaction (반응 - ultimate toxicants-target)
    + Target molecule(DNA, ptn, memb lipid, coenzyme)
    + Types of reactions
        + Non-covalent : hydrogen, memb receptor, PKC, acridine
        + Covalent
    + hydrogen abstract : 
        + R-SH -> RS*
        + CH3 -> CH2*, DNA -> C4 radical, lipid - lipid peroxidation
    + effects of toicants on targets 
        + dysfunction of target (mimicking endogenous ligands, morphine(opiate receptor), protein function impairment    
        + destruction of targets    
        + cellular dysfunction
        + TK, GPCR, Hormone receptor    
        + excitable cell dysfunction - alternation of signal
        + cocaine (adrenergic vasoconstriction)
- Toxic alternation
    + Mechanism of apoptosis 
            + ATP depletion, Ca increase, overpopulation of ROS(PARP increase - DNA injury))    
    + Protein repair(ubi, autophagy)

### 면역독성	!
- 최경철: 충북대학교
- Introduction to WBC
- Introduction to lymphoid organs    
- Sentinal cells - MQ, DC, Mast cells 
- Structure of LN - B cell은 cortex에 존재함. Ag 만나 proliferation -> class switching (항체를 만든다, cortex에서)
- Structure of spleen - Red pulp (RBC), white pulp(WBC)
- Hypersensitivity reactions (과민반응) - I, II, III(혈관염), IV
- Quiz:
    1. Acquired immunity - B cells
    2. BCR -> antibody
    3. Helper T -> CD4
    4. major 2차면역기관 - A,E
- ICH.org - E2B, CTD, MedDra
- ICH S6 guideline - TDAR, phenotyping 등을 해야 한다.    
- S8 guideline (immunotoxicology studies) - STS (standard toxicology study) -> factors to consider in the eval of potential immunotoxicity
- Hapten (low MW, unpredictable, immunogenecity)
- Introduction to antibody
- Type II, III - no standard, non-clinical test (Coombs test)
- murine LLNA (local LN assay) - thymidine -> DNA 합성시 incorporation - beta counter로 잴 수 있다.
- Quiz:
    1. 면역독성 카테고리 포함 안되는것? - Abnormal APC (IS, IG, HS, AI)
    2. 면역조직 아닌거? - Thyroid gl.
    3. Type IV 과민증 (Buehler , maximization, optimization) 아닌것은? 
    4. Passive cutaneous anaphyl, maxi test - 동물은? guinea pig
    5. Autoimmunity 비이상적인 현상
    6. ImmunoSuppression 아닌 것은? myelosupp, 면역 기관 위축, serum globulin증가(wrong!), 감염증가     

### 독성시험과 통계 !!
- 이영주: 경희대학교
- 기술통계, 추측통계
- 대표값 + 산포도
- 산술평균 - 극단치에 영향을 많이 받음, 명목변수, 순위변수에는 부적합(예-암1기, 2기), skewed distribution에는 부적합
- 기하평균 - 분포가 한쪽으로 치우쳐 로그변환하여 사용하는 경우(Cmax), 곱셈으로 계산하는 값의 평균 (AUC)
- 대부분의 경우는 SD가 옳다. 산포성 SD. 통계처리시 SE. 추측통계시.
    + triplicate를 세번이상 하는 경우는 SE써도 된다.
- 추측통계 
    + 모수 - 모집단을 대표. 
    + 신뢰구간 point estimate 99%CI -> 더 넓어진다. (90% CI에 비해)
- 통계적 가설검증 (귀무가설을 기각) 
- 검정통계량 - 가설의 옳고 그름을 판단. - 계산.     
- t~alpha/2~ = 3.182 이상이면 H0(귀무가설) 기각영역
- Decision Tree
- 서열척도(ordinal scale) - 비모수적 Spearman, MW U test, Kruskal-Wallis

### 독성병리 !!
- 김용범:	안전성평가연구소
- 같은 동물인데도 병리가 다를 수 있다. (정상이 다를 수 있어.)
- 시험물질 관련 조직변화를 표로 작성하여 소견의 중요성을 판단
- periportal vacuolation. Artifact. inadequate artifact. 
- 부검 : 가장 중요함. 
- gross 소견 기술: 출혈보다 discoloration. 표준화 통일화
- 장기중량 측정. 
- 표준화된 방식으로 삭정( 잘라야 함. ) 같은 조직은 일관성 있게. 
- 독성병리학자. 표준화된 표로 정리할 수 있는 능력. 
- 대조군의 중요성 강조. 수컷 대조군- 수컷 고용량 - 저용량 순서로 한다. 
- 현미경 진단. 
    + STP. ESTP. BSTP. JSTP. 표준화를 위한 기관들. 
    + 위치. - necrosis, neuron, hippocampus, brain 
    + 분포 - 국소, 다소성, 미만성.
    + 병변 등급 - 주관적일 수 있다
    + Apoptosis- 세포막 손상 없다. necrosis - 광범위 세포막 손상 -> 염증
    + 병적과정 - 혈행 장애. 
    + 치유 및 수복 - 재생, 반흔(섬유화)
    + 적응 기전 : 위축, 비대, 과형성, 화생. 
    + 종양: 세포조절 안됨.
- Peer review
- 아급성 혹은 만성 설치류 독성 시험. 암수 대저군 1마리(25%) 임의 5마리 고농도(10%) : 모든 슬라이드 동료 검토
- Pathology working group. PWG. 병리전문가 패널. - 검토는 어떻게 수행? 각자의 의견을 투표. 의견이 틀릴때는 조율. 최종적으로 다수에 의해. 

### 비임상시험결과의 임상시험 연계 !!!!
- 반복투여가 중요함. (NOAEL) - 대조군 대비 부작용이 유의하게 증가하지 않는 최고용량. 생물학적 유의성이 중요. (통계적 유의성이 없더라도)
- FDA pregnancy categories, IARC Carcinogens classification (group 1, 2, 3, 4)
- 반복투여 독성 시험 NOAEL을 잘 잡잡기 위해 4번의 기회가 있다. 
- 단기(4주)~ pivotal. 
- 단기에서 독성을 잘 봐야함. 충분히 높은 용량으로 시작한 뒤에 낮춰가는 쪽으로 해야 함. 그 반대는 참 힘들것.
- Safety margin = NOAEL에서의 exposure / MRHD에서의 exposure
    + exposure가 중요하다.     
- 비임상시험의 적용
    + 누구를 대상으로? 최초 투여 용량은 어떻게 결정하는가? 용량 얼마씩 증량
    + 이런 질문이 비임상시험에서 나오게 된다.
- Phase 1a (FIH) 임상시험대상자 (환자 vs 건강인?)
    + 비임상시험 결과 -> Seriousness? measurable? -> if no, 환자관련 의약품. If yes, 건강한 시험대상자
- Clinical starting dose 설정법
- NOAEL/PAD based approach - estimating the maximum safe starting dose in initial clinical trials (2005-07)
    + 초기 임상개시 가능 최고 용량 (MRSD)
        1. 각 동물 종의 NOAEL결정
        1. HED 계산
        1. 가장 적당한 동물종 선정
        1. safety factor 적용
        1. MRSD의 산정
        1. PAD고려하여 선정.
- Human equivalent dose (HED) calculation             
    + 사람 용량으로 외삽하는 가장 적합한 방법을 사용하여 HED 산출. (체표면적에 따라서)
        mg/kg을 mg/m2으로 변경해 준다.
    + km mouse 3 rat 6 monkey 12 dog 20 human 37
    + h:Donkey:Monkey(rabbit):Rat:mouse = 1:2:3:6:12(mg/kg) = 동일 mg/m2
    + mouse 120mg/kg * 3/37 = human 10mg/kg, rat 60mg/kg = human 10mg/kg
- Most appropriate species selection 
    + 적당한 종을 사용해라. 잘 모를때는 더 민감한 동물 써라. HED가 더 낮은 동물을 선택하면 된다.        
- safety factor application - 좀 낮춰서 투약하자. 
    + Default safety factor = 10
- MRSD 산정(Maximum recommended starting dose)
- Quiz : rat 4주 반복 독성 시험에서의 NOAEL 60mg/kg. Rat는 appropriate, safety factor = 10.
    + 60mg/kg rat km = 6, human 36, 나누면 1mg/kg이 된다. 60kg라고 보면 60mg으로 하면 된다.
    + HED = 60mg/kg * 6/37 = human 10mg/kg
    + MRSD = HED / SF = 10/10 = 1mg/kg = 60mg    
- PAD (Pharmacologically active dose, PAD) 고려.
    + PAD = 3mg/kg일때 임상 초회 용량 30으로 할 수 있다.
- MABEL Guideline        
    + TGN1412 (CD28-Super Mab)
    + HED 16 mg/kg , safety factor 160    
    + 원숭이 NOAEL    = 50mg/kg (BSA based HED = 16mg/kg)
    + 원숭이 PAD = 2.5 - 25 mg/kg 원숭이 PAD-HED = 0.8 ~ 8 mg/kg , starting dose = 0.1mg/kg
    + 사고 이후의 주장들 1. 5ug/kg    2. 3ug/kg으로 해야한다. 3. receptor occupancy - antagonist는 90% receptor occupancy가 적합. agonist는 10% receptor occupancy면 충분함. 이를 위해서는 1ug/kg면 충분함.
    + MABEL 아마도 사람에게서 약효가 나타날 용량. Minimal anticipated biological effect level) 
    + 2007-06 새로운 가이드라인 제정됨.    
    + animal in vitro -> allometric equation 산출 - animal in vivo
    + human in vitro -> 적용 . human MABEL 산출
- PK-guided approach - dose대신 전신 노출(systemic exposure) 이용하여 동물 결과를 외삽(extrapolation)
    + SD ( starting dose) = AUC * CL~h~
    + NOAEL 비글에서 AUC 20ug\*hr/mL 예상되는 제거율은 CL~h~ = 15L/hr 효력의 차이는 0.1 EC50/EC50
- 건강인 아닌 악성 종양 환자에서의 starting dose
    + 항암제에서.. 주료.
    + ICH S9    
        + 57개의 임상시험을 다 분석했다. 여기서 나온 공식으로 계산.
- 임상-비임상 밀접한 관련.
    + 개별 임상시험의 특성 
- NOAEL/PAD based approach
- MRSD = NOAEL * (km~animal~/km~human~)/SF

## Session II 2016-08-23
### 오믹스 기반을 이용한 독성평가 !
- 최진희	서울시립대학교
- systems toxicology - science+engineering+computing **Multi-omics technology**
- biological model 만들어.
- in silico - combination - 더 넓은 독성 개념을 얻을 수 있어
- 개발의 platform으로 사용할 수 있음.
- Exposure -> molecular -> cellular -> organ responses -> organism responses -> population responses
- Integration is the key.    
- New regulation (i.e. REACH), TOX21, TOX CAST 
- adverse outcome pathway
- [Benchmarks in Toxicology](
https://www.toxicology.org/about/history/docs/poster_Benchmark.pdf)    

### 독성동태 및 대사 !!!
- speaker: 신소영(원광대 약학대학)
- Efficacy 의약품의 효능 - 약물활성(Activity, A), 감수성(Sensitivity, S), 약물농도(Concentration, C)
- 약물의 조직에서 농도대신 약물농도에 혈중 약물 농도 변화로 효능을 기술가능. (가정)
- ADME
- toxicokinetics - 정의 : 약효를 기대하지 않는 농약이나 일반 화학물질의 체내 동태
    + ICH 가이드라인 
    + 독성시험기준 정의 : 독성시험 수행시 시험물질의 전신노출도 평가하기 위해 약물동태학적 자료를 산출하는 시험.
- Model
    + 가장 간단한 모델만 사용할 것임        
    + 대부분의 약물은 one compartment model로 설명이 됨.
    + Compartment model, PBPK model
    + zero- and first-order elimination
- CL 
    + rate of elimination / concentration = dX/dt / C~p~ - 약물이 혈중에서 소실되는 속도를 혈중 약물 농도로 나누어준 값 = 
    + CL is dose divided by AUC
- F
    + 약물 또는 그 활성대사체가 제제로부터 전신 순환혈로 흡수되는 속도와 양의 비율
    + IV는 F=1
- 비선형성
    + 흡수 riboflavin(transporter GI 포화)
    + 높은 농도에서는 모든 효소가 포화되어 0차반응에 가까워짐
    + 낮은 혈중 농도에서는 1차반응에 가까워짐.
- Michaelis-Menten
    + 소실속도 = -dC/dt = V~max~C/K~m~+C    
    + 약물농도가 Km보다 훨씬 클때 -dC/dt = Vmax
    + 훨씬 작을때 -dC/dt = Vmax\*C/Km
    + 선형동태구간/비선형동태구간 


### 유전독성 및 발암성 !!
- speaker: 김지영(안전성평가연구소) fnkim@kitox.re.kr
- 3 primary test battery (OECD)
    + 화장품에 대한 독성자료 (유럽)는 안받고 있다. 화장품, 유럽은 염색체 빼고 해야함.
- ICH
- Aim of genetic toxicology testing 
    + Genotoxicigy, mutagenicity
- Forward mutation(braoder mutagen identification)
- Backward mutation(reversion) - more restricted and accurate
- TG490 
    + in vitro genetic toxicology test 
    + mouse lymphoma assay 
    + TK6 assay로 불리기도 한다.
- Chromosomal abberation 
    + 수적 이상
    + 구조적 이상
    + pre-S : chromosome abberration vs post-S : chromatid abberation
- In vivo genetic toxicology tests
    + Tests for primary DNA damage(3 battery에는 안들어가.)
        + Fast, single-strand breaks(SSB) and/or alkali-labile sites(ALS)
        + Liver and stomach were used. (가장 중요한 장기)
- Sens and spec
    + MN, CA, MLA는 specificity가 낮다. (S9 처리해서 phase I은 많이 하지만 phase II(detoxification)를 구현할 수 있는 in vitro시험은 없기 때문에 specificity 낮음)
- 발암성 시험
    + detection of potential to induce neoplastic lesions
    + 요구되지 않는 경우 - 악성종양치료제, 3년 이내 생존
- "예전거로 해주세요."
    + 개정된 시험이 더 고비용이기 때문에 요청하는 경우가 많다.
    + 그러나 그렇게 하면 안된다. 

### 신경독성 !
- 위명복: 강원대학교
- 산화적 손상에 대한 신경계 취약성
    + 항산화방어기전 중등도 낮음(catalase, GPx, vit-E)
    + tight junction 단백감소, MMP 간접활성
    + microglia에 의한 ROS 및 cytokine 생산.
- 신경손상 형태
    + neuronopathy -> gliosis (methyl mercury, Tins, MPTP(heroin))
    + myelionopathy
- TG: 설치류 신경독성평가, 발달 신경독성평가
- Neurotoxicity screening battery
    + Tier 1 - FOB, locomotor, GFAP ELISA, histopathology
    + Tier 2
- 비동물대체법(non-animal alternative methods)
    + 세포를 가지고 하는 것이다.
    + 대체한계성 - 모든 것을 대체할 수 없다.
- Stroke, parkinson, SCI, etc..
- CNS injury marker - BBB(Evan's), microglia(OX-42), etc..

### 식품의 위해도 평가	!
- 최시내 케이앤에이컨설팅
- 체내로 유입되는 양이 중요함
- 급성 섭취 노출량 예측 
    + 잔류량이 composite 분석 결과에 해당. 
- 노출 평가
- 용량-반응 관계 규명
    + extrapolation : high-dose -> low-dose
    + 기본 원칙 : threshold approach, non-threshold approach
    + Non threshold -> extrapolation
        + cancer potency = Q1star = upper bound 
    + Threshold approach - NOAEL 
        + NOAEL을 활용한 RfD의 유도
        + NOAEL or LOAEL / UF x MF ; UF = uncertainty factor
- Risk characterization
    + Threshold 
        + Hazard quotient = [exposure level] / [reference dose]
        + exposure와 reference dose는 동일한 노출 기간에 근거

### 생식발생독성	!
- 김종춘: 전남대학교
- segment I, II, III (KFDA, ICH)
    1. Fertility and early embryonic development study
    2. Embryo-fetal development study
    3. Peri- and postnatal development study 
- Segment I
    + Stage I ~ XIV - 56일 걸린다.
    + 같은 stage끼리 비교해야 함.
- Segment II
    + 기형변이 
    + teratogenesis
    + 600kda 이하의 분자량이어야 태반 통과.
    + 연골 + 경골의 염색    
- Segment III
    + 한배새끼관찰, F1 성장, 행동, 생식기능시험
- Key point
    + 생식발생 위해성 급증
    + 시험법
    + 실험동물 종과 계통 선택
    + 결과의 해석
    + 종류와 특성 및 작용 기전
    + 3Rs principle

